library(shiny)
library(shinyjs)
library(shinythemes)
library(RMariaDB)
library(DBI)
library(shinymanager)
library(sodium)
library(shinyauthr)

options(shiny.reactlog = TRUE)
shiny::reactiveConsole(TRUE)